### ISSUE TITLE
Running SentiCR

### ISSUE THREAD

**Issue by kmn5409** [senticr/SentiCR#2]
Hi I am trying to use SentiCR but when I run it I'm getting the error
```bash
keanu@keanu-Inspiron-5567:~/temp/augur_push/augur5/senticr/SentiCR/SentiCR$ python SentiCR.py 
Cross validation
Algrithm: GBT
Repeat: 100
.............................
Run# 0
Using split-1 as test data..
Training classifier model..
Traceback (most recent call last):
  File "SentiCR.py", line 352, in <module>
    (precision, recall, f1score, accuracy)=ten_fold_cross_validation(oracle_data,ALGO)
  File "SentiCR.py", line 292, in ten_fold_cross_validation
    classifier_model=SentiCR(algo=ALGO,training_data= dataset[train])
  File "SentiCR.py", line 196, in __init__
    self.model = self.create_model_from_training_data()
  File "SentiCR.py", line 229, in create_model_from_training_data
    comments = preprocess_text(sentidata.text)
  File "SentiCR.py", line 175, in preprocess_text
    comments = expand_contractions(comments)
  File "SentiCR.py", line 107, in expand_contractions
    return contractions_regex.sub(replace, s.lower())
TypeError: cannot use a string pattern on a bytes-like object
```

Attached is a screenshot, I'm running it on Ubuntu 16.04 and using python 3
![screenshot from 2018-08-14 11-22-47](https://user-images.githubusercontent.com/27737729/44101133-b8a48002-9fb4-11e8-9b8a-ca9eb478cdba.png)

**Comment by nasifimtiazohi** [comment]
replacing
`comments = text.encode('ascii', 'ignore')` 
at line 174 in SentiCR.py with
`comments = text.encode('ascii', 'ignore').decode('utf-8')` 
might help

**Comment by kmn5409** [comment]
Okay thanks that worked.
